platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"

pod 'ReactiveCocoa', '2.5'

pod 'FMDB'

pod 'FMDBMigrationManager'

pod 'pop', '~> 1.0'

pod "JDFPeekaboo"

pod 'PARTagPicker'

pod 'SWTableViewCell', '~> 0.3.7'

pod "AKPickerView"

pod 'UIColor+MLPFlatColors', '~> 1.0'

pod "ASCFlatUIColor"

pod 'ZLSwipeableView'

pod 'Masonry'

pod 'SDWebImage', '~>3.6'

pod 'FlatUIKit'

pod "GCDObjC"

pod 'KVOController'

pod "AFViewShaker", "~> 0.0.2"

pod 'FTGNotificationController'

target :FATodosTests, :exclusive => true do
    pod 'Kiwi'
end

pod 'DateTools'

pod 'iOS7Colors', '~> 2.0.0'

pod 'ZLSwipeableView'

pod 'CocoaLumberjack'

pod 'XHRealTimeBlur'

pod 'PopMenu'

